config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => 'localhost:3000'
  root :to => 'pages#show', page: 'home'

  get '/pages/:page' => 'pages#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  resources :keystores, except: [:edit, :update]
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  get '/charges/edit', to: 'charges#edit'
  post '/charges/edit', to: 'charges#update'
  post 'charges/update_sub' => 'charges#update_sub'
  resources :charges, except: [:edit, :update]

end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :reset_token

  has_many :keystores, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, :uniqueness => {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
  validates :name, :presence => true
  validates :email, :presence => true,
            if: lambda { new_record? || !password.blank? }
  validates :password, :length => {minimum: 8}
  validates :password, :presence => true,
            if: lambda { new_record? || !password.blank? }

  before_save :save_uppercase
  before_create :confirmation_token


  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_digest = SecureRandom.urlsafe_base64.to_s
    update_attribute(:reset_digest, reset_digest)
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver
  end

  def update_membership(tf)
    if tf
      self.stripe_end_date = Date.today + 1.month
      save!(:validate => false)
    end
  end

  def has_valid_membership?
    stripe_end_date && Date.today <= stripe_end_date
  end

  has_secure_password

  private

  def save_uppercase
    self.name.upcase!
    self.email.upcase!
  end

  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate_user, only: [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    redirect_to root_url
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        flash[:success] = 'Welcome to Ressit! Please confirm your email
        address to begin uploading keystores.'
        login @user
        format.html { redirect_to keystores_path }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      login user
      flash[:success] = 'Your email has been confirmed. Welcome!'
      redirect_to keystores_path
    else
      flash.now[:error] = 'Invalid action.'
      redirect_to root_url
    end
  end

  private


  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def authenticate_user
    @user = User.find(params[:id])
    if !(@user && logged_in? && current_user.id == @user.id)
      flash.now[:error] = 'Not authorized.'
      redirect_to root_url
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user
            from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field form-group">
      <%= f.label :password_digest %>
      <%= f.text_field :password_digest %>
    </div>


    <%= button_tag(type: 'submit', class: 'actions btn btn-primary') do %>
        <i class="icon-ok icon-white"></i> Save Keystore
    <% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= form_for @user do |f| %>

    <div class="field form-group">
      Name: <%= f.text_field :name, class: 'form-control' %> <br>
    </div>

    <div class="field form-group">
      Password: <%= f.password_field :password, class: 'form-control' %> <br>
    </div>

    <div class="field form-group">
      Password Confirmation: <%= f.password_field :password_confirmation,
                                                  class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= link_to 'Cancel', current_user, class: 'btn btn-primary', style:
          'color:white' %>
      <%= f.submit 'Update!', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password digest</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

    <div class="form-group">
      Name: <%= f.text_field :name, class: 'form-control' %> <br>
    </div>
    <div class="form-group">
      Email: <%= f.text_field :email, class: 'form-control' %> <br>
    </div>
    <div class="form-group">
      Password: <%= f.password_field :password, class: 'form-control' %> <br>
    </div>
    <div class="field form-group">
      Password Confirmation: <%= f.password_field :password_confirmation,
                                                  class: 'form-control'
    %> <br>
    </div>
    <div class="form-group">
      <%= button_tag(type: 'submit', class: 'actions btn btn-primary') do %>
          <i class="icon-ok icon-white"></i> Sign Up!
      <% end %>
    </div>

<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Name:</strong>
  <%= @user.name %>
</h3>

<h3>
  <strong>Email:</strong>
  <%= @user.email %>
</h3>

<h3>
  <strong>Subscription Valid Until:</strong>
  <%= @user.stripe_end_date %>
</h3>

<h3>
  Email Confirmed:
  <% if @user.email_confirmed? %>
  <span style="color:green"
        class="glyphicon glyphicon-thumbs-up"></span>
  <% else %>
      <span style="color:red" class="glyphicon glyphicon-thumbs-down"></span>
  <% end %>
</h3>


<%= link_to 'Edit Profile Settings', edit_user_path(@user), class: 'btn
btn-primary', style: 'color:white' %>

<br>
<br>

<% if current_user && current_user.stripe_cus_id.nil? %>
    <%= link_to 'Payment Settings', new_charge_path, class: 'btn
btn-primary', style: 'color:white' %>
<% else %>
    <%= link_to 'Payment Settings', '/charges/edit', class: 'btn
btn-primary', style: 'color:white' %>
<% end %>