config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => 'localhost:3000'
  root :to => 'pages#show', page: 'home'

  get '/pages/:page' => 'pages#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  resources :keystores, except: [:edit, :update]
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  get '/charges/edit', to: 'charges#edit'
  post '/charges/edit', to: 'charges#update'
  post 'charges/update_sub' => 'charges#update_sub'
  resources :charges, except: [:edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keystor.es</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://bootswatch.com/united/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
  <!--<script src="http://malsup.github.io/jquery.cycle.all.js"></script>-->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Keystor.es', '/pages/home', {class: 'navbar-brand'} %>
      <!--<a class="navbar-brand" href="#">Keystore.io</a>-->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
            <li><%= link_to 'My Keystores', keystores_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                 role="button" aria-haspopup="true" aria-expanded="false"><%=
                @current_user.name %><span
              class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', @current_user %></li>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<!--<%= debug(params) if Rails.env.development? %>-->
<!--<%= debug(flash) if Rails.env.development? %>-->
<div class="container">
  <%= yield %>
</div>


<div class="navbar navbar-default navbar-fixed-bottom footer">
  <div class="container">
    <p class="navbar-text pull-left">2017 - Built and Managed By J. Colby Cox
      <!--<a href="http://tinyurl.com/tbvalid" target="_blank">HTML 5 Validation</a>-->
    </p>

    <a href="https://github.com/coxjc/keystor.es">
        <span style="color:white; text-decoration:underline;" class="navbar-text pull-right">
            Github Repo
      </span>
    </a>
  </div>

</div>

</body>
</html>

app/views/layouts/changes.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<%= yield %>
</body>
</html>